print("this is a python file")
print("this python file is included so that the 'contributions' section of the github says that I made code additions")
print("without this python file krueger will dock me points for few contributions")
print("please refrain for the time being from deleting this file")

import turtle

turtle.setup(400,100)
board = turtle.Turtle()
board.color("black")
board.pensize(10)
board.penup()
board.setpos(20,-66)
board.pendown()
board.circle(80)
turtle.setup(100,100)
board.penup()
board.setpos(180,-66)
board.pendown()
board.circle(80)
board.penup()
board.setpos(150,85)
board.pendown()
board.left(90)
board.forward (300)
board.circle(50,180)
board.forward(300)
board.penup()
board.pencolor("black")
board.setpos(100,427)
board.pendown()
board.forward(30)
board.left(90)
board.pencolor("black")
board.pensize(8)
board.forward (50)
board.left (180)
board.forward (100)
