CREATE TABLE team_vs_team (

    team_season varchar CONSTRAINT team_season_key PRIMARY KEY,
    ATL numeric,
    BOS numeric,
    BRK numeric,
    CHI numeric,
    CHA numeric,
    CLE numeric,
    DAL numeric,
    DEN numeric,
    DET numeric,
    GSW numeric,
    HOU numeric,
    IND numeric,
    LAC numeric,
    LAL numeric,
    MEM numeric,
    MIA numeric,
    MIL numeric,
    MIN numeric,
    NOP numeric,
    NYK numeric,
    OKC numeric,
    ORL numeric,
    PHI numeric,
    PHO numeric,
    POR numeric,
    SAC numeric,
    SAS numeric,
    TOR numeric,
    UTA numeric,
    WAS numeric
    
    );

