CREATE TABLE team_vs_team (

    team varchar CONSTRAINT team_key PRIMARY KEY,
    ATL varchar NOT NULL,
    BOS varchar NOT NULL,
    BRK varchar NOT NULL,
    CHI varchar NOT NULL,
    CHO varchar NOT NULL,
    CLE varchar NOT NULL,
    DAL varchar NOT NULL,
    DEN varchar NOT NULL,
    DET varchar NOT NULL,
    GSW varchar NOT NULL,
    HOU varchar NOT NULL,
    IND varchar NOT NULL,
    LAC varchar NOT NULL,
    LAL varchar NOT NULL,
    MEM varchar NOT NULL,
    MIA varchar NOT NULL,
    MIL varchar NOT NULL,
    MIN varchar NOT NULL,
    NOP varchar NOT NULL,
    NYK varchar NOT NULL,
    OKC varchar NOT NULL,
    ORL varchar NOT NULL,
    PHI varchar NOT NULL,
    PHO varchar NOT NULL,
    POR varchar NOT NULL,
    SAC varchar NOT NULL,
    SAS varchar NOT NULL,
    TOR varchar NOT NULL,
    UTA varchar NOT NULL,
    WAS varchar NOT NULL
    
    );
